name: Deploy to GCP Artifact Registry

on:
  push:
    branches: [ main, master, develop, staging, release/* ]
  pull_request:
    branches: [ main, master, develop, staging ]

env:
  REGISTRY: us-central1-docker.pkg.dev
  REPOSITORY: landing-fardust/public-docker

permissions:
  contents: read
  id-token: write

jobs:
  discover-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles: ${{ steps.get-dockerfiles.outputs.files }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Dockerfiles
      id: get-dockerfiles
      run: |
        # Find all Dockerfiles in the images directory
        dockerfiles=$(find images -name "Dockerfile" -type f | jq -R -s -c 'split("\n")[:-1]')
        echo "files=$dockerfiles" >> $GITHUB_OUTPUT

  determine-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
    steps:
    - name: Determine version and tag
      id: version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          # Tag-based versioning (for manual releases)
          tag_name=${GITHUB_REF#refs/tags/}
          version=${tag_name#v}
          tag=$tag_name
        else
          # Branch-based versioning
          branch_name=${GITHUB_REF#refs/heads/}
          
          # For main/master, use semantic versioning
          if [[ "$branch_name" == "main" || "$branch_name" == "master" ]]; then
            # Use commit SHA for version to ensure uniqueness
            short_sha=${GITHUB_SHA::8}
            version="0.0.0-$short_sha"
            tag="main-$short_sha"
          else
            # For other branches, use branch name
            version="0.0.0-$branch_name"
            tag="branch-$branch_name"
          fi
        fi
        
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT

  build-images:
    needs: [discover-dockerfiles, determine-version]
    strategy:
      matrix:
        dockerfile: ${{ fromJSON(needs.discover-dockerfiles.outputs.dockerfiles) }}
    uses: ./.github/workflows/reusable-build.yml
    with:
      dockerfile: ${{ matrix.dockerfile }}
      version: ${{ needs.determine-version.outputs.version }}
      tag: ${{ needs.determine-version.outputs.tag }}
    secrets:
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}

 